- id: prettier
  name: prettier
  description: ""
  entry: prettier --write --ignore-unknown --single-quote=false
  language: node
  types: [file]
  args: []
  require_serial: false
  additional_dependencies: ["prettier@3.3.3"]
  minimum_pre_commit_version: "0"
